name: Django CI

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest
    #strategy:
    #  max-parallel: 5
    #  matrix:
    #    python-version: [3.7, 3.8, 3.9, 3.11, 3.12]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: 3.11 #${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
#    - name: Run Tests
#      run: |
#        python manage.py pytest
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.11
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: |
          shopt -s globstar && pylint --load-plugins pylint_django --django-settings-module=anynote.settings **/*.py
